#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

#----- FUNCTIONS -----#

. $dir/functions/sublime3

# THIRD PARTY APPLICATIONS
function thirdparty {
echo ''
show_info 'What would you like to install?'
echo ''
echo '1. Google Chrome?'
echo '2. Google Talk Plugin?'
echo '3. Nautilus Dropbox?'
echo '4. Sublime Text?'
echo '5. Qgis?'
echo '6. RStudio?'
echo 'r. Return'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# Google Chrome
1) 
    echo 'Downloading Google Chrome...'
    cd $HOME/Downloads
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Google Chrome...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y google-chrome*.rpm
    # Cleanup and finish
    rm google-chrome*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Google Talk Plugin
2)
    echo 'Downloading Google Talk Plugin...'
    cd $HOME/Downloads
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://dl.google.com/linux/direct/google-talkplugin_current_i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://dl.google.com/linux/direct/google-talkplugin_current_x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Google Talk Plugin...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y google-talkplugin_current*.rpm
    # Cleanup and finish
    rm google-talkplugin_current*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Dropbox
3)
    echo 'Downloading Dropbox...'
    cd $HOME/Downloads
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://linux.dropbox.com/packages/fedora/nautilus-dropbox-1.6.0-1.fedora.i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://linux.dropbox.com/packages/fedora/nautilus-dropbox-1.6.0-1.fedora.x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Dropbox...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y nautilus-dropbox-*.rpm
    # Cleanup and finish
    rm nautilus-dropbox-*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Sublime Text 3
4)
    sublime3
    ;;
# Qgis
5)
    echo 'Downloading Qgis...'
    cd $HOME/Downloads
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://linux.dropbox.com/packages/fedora/nautilus-dropbox-1.6.0-1.fedora.i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://linux.dropbox.com/packages/fedora/nautilus-dropbox-1.6.0-1.fedora.x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Dropbox...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y nautilus-dropbox-*.rpm
    # Cleanup and finish
    rm nautilus-dropbox-*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# RStudio
6)
    echo 'Downloading RStudio...'
    cd $HOME/Downloads
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://download1.rstudio.org/rstudio-0.99.465-i686.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://download1.rstudio.org/rstudio-0.99.465-x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing RStudio...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y rstudio-*.rpm
    # Cleanup and finish
    rm rstudio-*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && echo 'Not an option, try again.' && thirdparty;;
esac
}
