#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

#----- FUNCTIONS -----#

. $dir/functions/sublime3

# THIRD PARTY APPLICATIONS
function thirdparty {
echo ''
show_info 'What would you like to install?'
echo ''
echo '1. Google Chrome?'
echo '2. Google Talk Plugin?'
echo '3. Nautilus Dropbox?'
echo '4. Insync?'
echo '5. Sublime Text?'
echo '6. Atom'
echo '7. RStudio?'
echo '8. TexLive?'
echo '9. Netlogo?'
echo '10. Gama?'
echo 'r. Return'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# Google Chrome
1)
    echo 'Downloading Google Chrome...'
    cd $HOME/Téléchargements
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Google Chrome...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y google-chrome*.rpm
    # Cleanup and finish
    rm google-chrome*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Google Talk Plugin
2)
    echo 'Downloading Google Talk Plugin...'
    cd $HOME/Téléchargements
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://dl.google.com/linux/direct/google-talkplugin_current_i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://dl.google.com/linux/direct/google-talkplugin_current_x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Google Talk Plugin...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y google-talkplugin_current*.rpm
    # Cleanup and finish
    rm google-talkplugin_current*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Dropbox
3)
    echo 'Downloading Dropbox...'
    cd $HOME/Téléchargements
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://linux.dropbox.com/packages/fedora/nautilus-dropbox-1.6.0-1.fedora.i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://linux.dropbox.com/packages/fedora/nautilus-dropbox-1.6.0-1.fedora.x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Dropbox...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y nautilus-dropbox-*.rpm
    # Cleanup and finish
    rm nautilus-dropbox-*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;

# Insync
  4)
    echo 'Downloading insync...'
    cd $HOME/Téléchargements
    # Download RPM file that matches system architecture
  if [ $(uname -i) = 'i386' ]; then
      curl -O http://s.insynchq.com/builds/insync-1.3.14.36131-fc21.i686.rpm
  elif [ $(uname -i) = 'x86_64' ]; then
      curl -O http://s.insynchq.com/builds/insync-1.3.14.36131-fc21.x86_64.rpm
  fi
  # Install package(s)
  echo 'Installing insync...'
  show_info 'Requires root privileges:'
  sudo dnf --nogpgcheck install -y insync-*.rpm
  # Cleanup and finish
  rm insync-*.rpm
  cd
  show_success 'Done.'
  thirdparty
  ;;

# Sublime Text 3
5)
    sublime3
    ;;
# Atom
6)
echo 'Downloading Atom.io...'
cd $HOME/Téléchargements
# Download RPM file that matches system architecture
if [ $(uname -i) = 'i386' ]; then
    curl -O https://atom.io/download/rpm
elif [ $(uname -i) = 'x86_64' ]; then
    curl -O https://atom.io/download/rpm
fi
# Install package(s)
echo 'Atom ...'
show_info 'Requires root privileges:'
sudo dnf --nogpgcheck install -y atom*.rpm
# Cleanup and finish
rm atom*.rpm
cd
show_success 'Done.'
thirdparty
;;
# RStudio
7)
    echo 'Downloading RStudio...'
    cd $HOME/Téléchargements
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://download1.rstudio.org/rstudio-0.99.465-i686.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://download1.rstudio.org/rstudio-0.99.465-x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing RStudio...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y rstudio-*.rpm
    # Cleanup and finish
    rm rstudio-*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# TexLive
8)
    echo 'Downloading TexLive...'
    cd $HOME/Téléchargements
    # Download perl install file
    wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
    #Unpacke the tar.gz file
    tar xf install-tl-unx.tar.gz && mv install-tl-*/ install-tl
    cd install-tl
    # Install package(s)
    echo 'Installing TexLive...'
    show_info 'Requires root privileges:'
    sudo ./install-tl
    #defined path in bashrc
    echo 'PATH=/usr/local/texlive/2016/bin/x86_64-linux/:$PATH; export PATH ' >> ~/.bashrc
    echo 'MANPATH=/usr/local/texlive/2016/texmf-dist/doc/man:$MANPATH; export MANPATH' >> ~/.bashrc
    echo 'INFOPATH=/usr/local/texlive/2016/texmf-dist/doc/info:$INFOPATH; export INFOPATH' >> ~/.bashrc
    # Cleanup and finish
    cd ..
    rm -R install-tl*
    cd ~
    show_success 'Done.'
    thirdparty
    ;;
# Netlogo
9)
    echo 'Downloading Netlogo...'
    cd $HOME/Téléchargements
    # Download perl install file
    wget --no-check-certificate https://ccl.northwestern.edu/netlogo/6.0/NetLogo-6.0-64.tgz
    #Unpacke the tar.gz file
    tar -xf NetLogo-6.0-64.tgz
    echo 'Installing Netlogo...'
    show_info 'Requires root privileges:'
    sudo cp -R NetLogo-6.0-64 /opt/
    # Create symbolic link
	  echo 'Creating symbolic link...'
    show_info 'Requires root privileges:'
    sudo ln -sf /opt/NetLogo-6.0-64/NetLogo\ 6.0/NetLogo /usr/bin/netlogo
    sudo chmod +x /usr/bin/netlogo
    show_success 'Done.'
    #defined path in bashrc
    echo "alias netlogo='/opt/NetLogo-6.0-64/NetLogo\ 6.0/NetLogo'" >> ~/.bashrc

    # Cleanup and finish
    rm -R netlogo*
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Gama
10)
    echo 'Downloading Gama...'
    cd $HOME/Téléchargements
    # Download perl install file
    wget http://51.255.46.42/releases/gama1_7_b1_linux64.zip
    #Unpacke the tar.gz file
    unzip gama1_7_b1_linux64.zip
    echo 'Installing Gama...'
    show_info 'Requires root privileges:'
    sudo cp -R gama1_7_linux64 ~/app/
    # Create symbolic link
	echo 'Creating symbolic link...'
	show_info 'Requires root privileges:'
	sudo ln -sf ~/app/gama1_7_linux64/Gama /usr/bin/gama
	sudo chmod +x /usr/bin/gama
	show_success 'Done.'
    #defined path in bashrc
    #echo "alias gama='sh ~/app/netlogo-5.2.0/netlogo.sh'" >> ~/.bashrc

    # Cleanup and finish
    rm -R gama1*
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Return
[Rr]*)
    clear && main;;
# Invalid choice
* )
    clear && echo 'Not an option, try again.' && thirdparty;;
esac
}
