#!/bin/bash

#----- DECLARATIONS -----#

dir="$(dirname "$0")"

#----- FUNCTIONS -----#

. $dir/functions/sublime3

# THIRD PARTY APPLICATIONS
function thirdparty {
echo ''
show_info 'What would you like to install?'
echo ''
echo '1. Google Chrome?'
echo '2. Google Talk Plugin?'
echo '3. Nautilus Dropbox?'
echo '4. Sublime Text?'
echo '5. RStudio?'
echo '6. TexLive?'
echo '7. Netlogo?'
echo 'r. Return'
echo ''
show_info 'Enter your choice:' && read REPLY
case $REPLY in
# Google Chrome
1) 
    echo 'Downloading Google Chrome...'
    cd $HOME/Downloads
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Google Chrome...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y google-chrome*.rpm
    # Cleanup and finish
    rm google-chrome*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Google Talk Plugin
2)
    echo 'Downloading Google Talk Plugin...'
    cd $HOME/Downloads
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://dl.google.com/linux/direct/google-talkplugin_current_i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://dl.google.com/linux/direct/google-talkplugin_current_x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Google Talk Plugin...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y google-talkplugin_current*.rpm
    # Cleanup and finish
    rm google-talkplugin_current*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Dropbox
3)
    echo 'Downloading Dropbox...'
    cd $HOME/Downloads
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://linux.dropbox.com/packages/fedora/nautilus-dropbox-1.6.0-1.fedora.i386.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://linux.dropbox.com/packages/fedora/nautilus-dropbox-1.6.0-1.fedora.x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing Dropbox...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y nautilus-dropbox-*.rpm
    # Cleanup and finish
    rm nautilus-dropbox-*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Sublime Text 3
4)
    sublime3
    ;;
# RStudio
5)
    echo 'Downloading RStudio...'
    cd $HOME/Downloads
    # Download RPM file that matches system architecture
    if [ $(uname -i) = 'i386' ]; then
        curl -O https://download1.rstudio.org/rstudio-0.99.465-i686.rpm
    elif [ $(uname -i) = 'x86_64' ]; then
        curl -O https://download1.rstudio.org/rstudio-0.99.465-x86_64.rpm
    fi
    # Install package(s)
    echo 'Installing RStudio...'
    show_info 'Requires root privileges:'
    sudo dnf --nogpgcheck install -y rstudio-*.rpm
    # Cleanup and finish
    rm rstudio-*.rpm
    cd
    show_success 'Done.'
    thirdparty
    ;;
# TexLive
6)
    echo 'Downloading TexLive...'
    cd $HOME/Downloads
    # Download perl install file
    wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
    #Unpacke the tar.gz file
    tar xf install-tl-unx.tar.gz && mv install-tl-*/ install-tl
    cd install-tl
    # Install package(s)
    echo 'Installing TexLive...'
    show_info 'Requires root privileges:'
    sudo ./install-tl
    #defined path in bashrc
    echo 'PATH=/usr/local/texlive/2015/bin/x86_64-linux/:$PATH; export PATH ' >> ~/.bashrc
    echo 'MANPATH=/usr/local/texlive/2015/texmf-dist/doc/man:$MANPATH; export MANPATH' >> ~/.bashrc
    echo 'INFOPATH=/usr/local/texlive/2015/texmf-dist/doc/info:$INFOPATH; export INFOPATH' >> ~/.bashrc
    # Cleanup and finish
    cd ..
    rm -R install-tl*
    cd
    show_success 'Done.'
    thirdparty
    ;;
# TexLive
7)
    echo 'Downloading Netlogo...'
    cd $HOME/Downloads
    # Download perl install file
    wget https://ccl.northwestern.edu/netlogo/5.2.0/netlogo-5.2.0.tar.gz
    #Unpacke the tar.gz file
    tar -xf netlogo-5.2.0.tar.gz
    echo 'Installing Netlogo...'
    show_info 'Requires root privileges:'
    sudo cp -R netlogo-5.2.0 /opt/
    #defined path in bashrc
    echo "alias netlogo='sh /opt/netlogo-5.2.0/netlogo.sh'" >> ~/.bashrc
    
    # Cleanup and finish
    rm -R netlogo*
    cd
    show_success 'Done.'
    thirdparty
    ;;
# Return
[Rr]*) 
    clear && main;;
# Invalid choice
* ) 
    clear && echo 'Not an option, try again.' && thirdparty;;
esac
}
